[package]
name = "hns"
version = "0.2.0"
edition = "2021"
readme = "README.md"
description = "Human numeric sorting program — does what `sort -h` is supposed to do!"
repository = "https://github.com/ctrlcctrlv/humnumsort"
license = "Apache-2.0"
categories = ["command-line-utilities", "text-processing", "algorithms"]
authors = ["Fredrick Brennan <copypaste@kittens.ph>", "`humnumsort` Project Authors"]
keywords = ["coreutils", "numeric-sorting", "human-numeric-sort", "stdin", "stdout"]

[dependencies]
log = "0.4"
env_logger = "0.9"
humnum = { version = ">=0", path = "../lib" }

[package.metadata.deb]
assets = [
    ["target/release/hns", "usr/bin/hns", "755"],
    ["target/release/hns", "usr/bin/hns+", "755"],
    ["target/release/hns", "usr/bin/hxs", "755"],
    ["../doc/hns.1.gz", "usr/share/man/man1/hns.1.gz", "644"],
    ["../README.md", "usr/share/doc/hns/readme", "644"],
    ["../doc/hns.1.html", "usr/share/doc/hns/manpage.html", "644"]
]
preserve-symlinks = true
section = "Utilities"

[features]
force_color = ["humnum/force_color"]

[package.metadata.generate-rpm]
assets = [
    { source = "../target/release/hns", dest = "/usr/bin/hns", mode = "755" },
    { source = "../target/release/hns", dest = "/usr/bin/hns+", mode = "755" },
    { source = "../target/release/hns", dest = "/usr/bin/hxs", mode = "755" },
    { source = "../doc/hns.1.gz", dest = "/usr/share/man/man1/", mode = "644" },
]
