.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH humnum 1  "humnum 0.1.0" 
.SH NAME
humnum \- ``Human numerically\*(Aq\*(Aq sorts.
.SH SYNOPSIS
\fBhumnum\fR <\fIsubcommands\fR>
.SH DESCRIPTION
.PP
A "human numeric" sorting program — does what `sort \-h` is supposed to do!
.PP
(That is to say, it does what you likely already thought or may\*(Aqve assumed GNU/BSD `sort \-h` does.)
.SH SUBCOMMANDS
.TP
humnum\-hns(1)
``Human numerically\*(Aq\*(Aq sorts.
.TP
humnum\-hns+(1)
``Human numerically\*(Aq\*(Aq sorts. (no negatives)
.SH EXTRA

.SH VERSION
v0.1.0
.SH AUTHORS
Fredrick Brennan <copypaste@kittens.ph>, `humnumsort` Project Authors
